export * from './admins.service';
import { AdminsService } from './admins.service';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './doNotUse.service';
import { DoNotUseService } from './doNotUse.service';
export * from './email.service';
import { EmailService } from './email.service';
export * from './hackathons.service';
import { HackathonsService } from './hackathons.service';
export * from './main.service';
import { MainService } from './main.service';
export * from './nomination.service';
import { NominationService } from './nomination.service';
export * from './projectApplications.service';
import { ProjectApplicationsService } from './projectApplications.service';
export * from './projectComments.service';
import { ProjectCommentsService } from './projectComments.service';
export * from './projectPosts.service';
import { ProjectPostsService } from './projectPosts.service';
export * from './projectTeamMembers.service';
import { ProjectTeamMembersService } from './projectTeamMembers.service';
export * from './projects.service';
import { ProjectsService } from './projects.service';
export * from './projectsHackathon.service';
import { ProjectsHackathonService } from './projectsHackathon.service';
export * from './reservedNicknames.service';
import { ReservedNicknamesService } from './reservedNicknames.service';
export * from './resumes.service';
import { ResumesService } from './resumes.service';
export * from './search.service';
import { SearchService } from './search.service';
export * from './tags.service';
import { TagsService } from './tags.service';
export * from './teamMembersHackathon.service';
import { TeamMembersHackathonService } from './teamMembersHackathon.service';
export * from './users.service';
import { UsersService } from './users.service';
export * from './vacancies.service';
import { VacanciesService } from './vacancies.service';
export const APIS = [AdminsService, AuthService, DoNotUseService, EmailService, HackathonsService, MainService, NominationService, ProjectApplicationsService, ProjectCommentsService, ProjectPostsService, ProjectTeamMembersService, ProjectsService, ProjectsHackathonService, ReservedNicknamesService, ResumesService, SearchService, TagsService, TeamMembersHackathonService, UsersService, VacanciesService];
