/**
 * Uteam API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestInfoDto } from './requestInfoDto';


export interface ErrorResponseDto { 
    httpStatus?: number;
    userMessage?: string;
    details?: string;
    exception?: string;
    timestamp?: string;
    stackTrace?: string;
    requestInfo?: RequestInfoDto;
}

