/**
 * Uteam API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectDto } from './projectDto';
import { UserDto } from './userDto';


export interface PostDto { 
    id?: number;
    title?: string;
    imageLink?: string;
    content?: string;
    createdAt?: string;
    updatedAt?: string;
    project?: ProjectDto;
    author?: UserDto;
    likesCount?: number;
    dislikesCount?: number;
}

