/**
 * Uteam API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProjectFilterDto { 
    type?: ProjectFilterDto.TypeEnum;
    cityId?: number;
}
export namespace ProjectFilterDto {
    export const TypeEnum = {
        Startup: 'STARTUP',
        Company: 'COMPANY',
        OneTimeProject: 'ONE_TIME_PROJECT'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


