/**
 * Uteam API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectDto } from './projectDto';
import { UserDto } from './userDto';
import { TagDto } from './tagDto';


export interface AdDto { 
    id?: number;
    title: string;
    user?: UserDto;
    profession: TagDto;
    skills: Set<TagDto>;
    motivations: Set<TagDto>;
    minPayment?: number;
    details?: string;
    visibility?: AdDto.VisibilityEnum;
    readonly creationDate?: string;
    banReason?: string;
    type?: AdDto.TypeEnum;
    projectDto?: ProjectDto;
    employment?: AdDto.EmploymentEnum;
    tags?: Set<TagDto>;
}
export namespace AdDto {
    export const VisibilityEnum = {
        Everybody: 'EVERYBODY',
        CreatorOnly: 'CREATOR_ONLY',
        Ban: 'BAN'
    } as const;
    export type VisibilityEnum = typeof VisibilityEnum[keyof typeof VisibilityEnum];
    export const TypeEnum = {
        Vacancy: 'VACANCY',
        Resume: 'RESUME'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
    export const EmploymentEnum = {
        Freelance: 'FREELANCE',
        Project: 'PROJECT'
    } as const;
    export type EmploymentEnum = typeof EmploymentEnum[keyof typeof EmploymentEnum];
}


