/**
 * Uteam API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {ITagDto, TagDto} from './tagDto';


export interface AdFilterDto {
    searchText?: string;
    userId?: number;
    userActivityStatuses?: Set<AdFilterDto.UserActivityStatusesEnum>;
    userEmploymentStatuses?: Set<AdFilterDto.UserEmploymentStatusesEnum>;
    genders?: Set<AdFilterDto.GendersEnum>;
    ageGte?: number;
    ageLte?: number;
    paymentGte?: number;
    cityIds?: Set<number>;
    regionIds?: Set<number>;
    districtIds?: Set<number>;
    tags?: Set<ITagDto>;
    visibilities?: Set<AdFilterDto.VisibilitiesEnum>;
    creationDateGte?: string;
    creationDateLte?: string;
    adType?: AdFilterDto.AdTypeEnum;
}
export namespace AdFilterDto {
    export const UserActivityStatusesEnum = {
        OpenToProposals: 'OPEN_TO_PROPOSALS',
        CanGiveAdvice: 'CAN_GIVE_ADVICE',
        NotActive: 'NOT_ACTIVE'
    } as const;
    export type UserActivityStatusesEnum = typeof UserActivityStatusesEnum[keyof typeof UserActivityStatusesEnum];
    export const UserEmploymentStatusesEnum = {
        Employed: 'EMPLOYED',
        Unemployed: 'UNEMPLOYED',
        Freelance: 'FREELANCE',
        OwnBusiness: 'OWN_BUSINESS'
    } as const;
    export type UserEmploymentStatusesEnum = typeof UserEmploymentStatusesEnum[keyof typeof UserEmploymentStatusesEnum];
    export const GendersEnum = {
        Male: 'MALE',
        Female: 'FEMALE'
    } as const;
    export type GendersEnum = typeof GendersEnum[keyof typeof GendersEnum];
    export const VisibilitiesEnum = {
        Everybody: 'EVERYBODY',
        CreatorOnly: 'CREATOR_ONLY',
        Ban: 'BAN'
    } as const;
    export type VisibilitiesEnum = typeof VisibilitiesEnum[keyof typeof VisibilitiesEnum];
    export const AdTypeEnum = {
        Vacancy: 'VACANCY',
        Resume: 'RESUME'
    } as const;
    export type AdTypeEnum = typeof AdTypeEnum[keyof typeof AdTypeEnum];
}


