/**
 * Uteam API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectDto } from './projectDto';
import { AdDto } from './adDto';


export interface ApplicationDto { 
    id?: number;
    coverLetter?: string;
    readonly createdAt?: string;
    projectDto?: ProjectDto;
    resume?: AdDto;
}

