/**
 * Uteam API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RegionDto } from './regionDto';


export interface CityDto { 
    id?: number;
    name?: string;
    region?: RegionDto;
}

