/**
 * Uteam API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HackathonProjectDto } from './hackathonProjectDto';
import { UserDto } from './userDto';


export interface HackathonTeamMemberDto { 
    id?: number;
    hackathonUserRole?: HackathonTeamMemberDto.HackathonUserRoleEnum;
    hackathonId?: number;
    hackathonProject?: HackathonProjectDto;
    user?: UserDto;
    createdAt?: string;
}
export namespace HackathonTeamMemberDto {
    export const HackathonUserRoleEnum = {
        HackathonAdmin: 'HACKATHON_ADMIN',
        HackathonProjectAdmin: 'HACKATHON_PROJECT_ADMIN',
        HackathonUser: 'HACKATHON_USER'
    } as const;
    export type HackathonUserRoleEnum = typeof HackathonUserRoleEnum[keyof typeof HackathonUserRoleEnum];
}


