/**
 * Uteam API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectDto } from './projectDto';
import { HackathonDto } from './hackathonDto';


export interface HackathonProjectDto { 
    id?: number;
    hackathon?: HackathonDto;
    project?: ProjectDto;
    createdAt?: string;
}

