/**
 * Uteam API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {UserDto} from "./userDto";


export interface IHackathonDto {
    id?: number;
    title: string;
    nickname?: string;
    imageLink?: string;
    shortDescription?: string;
    format: HackathonDto.FormatEnum;
    startDate: any;
    endDate: any;
    registrationStartDate?: any;
    registrationDeadline: any;
    registrationSuspended?: any;
    organizer: string;
    focus: string;
    targetAudience: string;
    participationConditions?: string;
    prizePool?: string;
    location?: string;
    hackathonLink?: string;
    customLink?: string;
    telegram?: string;
    registrationStatus: HackathonDto.RegistrationStatusEnum;
    createdAt?: string;
    hasApplied?: boolean;
    avatarLink?: string;
    creator: UserDto;
}

export enum RoleEnum {
  Admin  = 'HACKATHON_ADMIN',
  Moderator  = 'HACKATHON_PROJECT_ADMIN',
  User  = 'HACKATHON_USER',
}
export namespace HackathonDto {
    export const FormatEnum = {
        Online: 'ONLINE',
        Offline: 'OFFLINE',
        Hybrid: 'HYBRID'
    } as const;
    export type FormatEnum = typeof FormatEnum[keyof typeof FormatEnum];
    export const RegistrationStatusEnum = {
        Open: 'OPEN',
        Pending: 'PENDING',
        Closed: 'CLOSED'
    } as const;
    export type RegistrationStatusEnum = typeof RegistrationStatusEnum[keyof typeof RegistrationStatusEnum];
}


