/**
 * Uteam API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProjectVacancyFilterDto { 
    visibilities?: Set<ProjectVacancyFilterDto.VisibilitiesEnum>;
    vacancyOwnerBanned?: boolean;
}
export namespace ProjectVacancyFilterDto {
    export const VisibilitiesEnum = {
        Everybody: 'EVERYBODY',
        CreatorOnly: 'CREATOR_ONLY',
        Ban: 'BAN'
    } as const;
    export type VisibilitiesEnum = typeof VisibilitiesEnum[keyof typeof VisibilitiesEnum];
}


