/**
 * Uteam API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDto } from './userDto';
import { TeamMemberDto } from './teamMemberDto';
import { CityDto } from './cityDto';
import { AdDto } from './adDto';


export interface IProjectDto {
    id: number;
    nickname?: string;
    telegram?: string;
    email?: string;
    title?: string;
    summary?: string;
    description?: string;
    developmentStage?: string;
    tasks?: string;
    type?: ProjectDto.TypeEnum;
    avatarLink?: string;
    headerLink?: string;
    readonly likesCount?: number;
    readonly userLike?: boolean;
    readonly createdAt?: string;
    vacancies?: Array<AdDto>;
    owner?: UserDto;
    team?: Array<TeamMemberDto>;
    city?: CityDto;
    stack?: any[];
}
export namespace ProjectDto {
    export const TypeEnum = {
        Startup: 'STARTUP',
        Company: 'COMPANY',
        OneTimeProject: 'ONE_TIME_PROJECT'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


