/**
 * Uteam API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DistrictDto } from './districtDto';


export interface RegionDto { 
    id?: number;
    name?: string;
    district?: DistrictDto;
}

