/**
 * Uteam API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RequestInfoDto { 
    method?: string;
    details?: string;
    userId?: string;
    params?: { [key: string]: Array<string>; };
    headers?: { [key: string]: Array<string>; };
    body?: string;
    timestamp?: string;
}

