/**
 * Uteam API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ITagDto {
    id: number;
    name: string;
    nameEng?: string;
    competenceLevel?: number;
    type?: TagDto.TypeEnum;
    color?: string;
}
export namespace TagDto {
    export const TypeEnum = {
        Profession: 'PROFESSION',
        Skill: 'SKILL',
        Motivation: 'MOTIVATION'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


