/**
 * Uteam API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectDto } from './projectDto';
import { UserDto } from './userDto';


export interface TeamMemberDto { 
    id?: number;
    profession?: string;
    readonly createdAt?: string;
    projectDto?: ProjectDto;
    user?: UserDto;
}

