/**
 * Uteam API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {IProjectDto, ProjectDto} from './projectDto';
import { UserDto } from './userDto';


export interface TeamMemberDto {
    id?: number;
    profession?: string;
    readonly createdAt?: string;
    projectDto?: IProjectDto;
    user?: UserDto;
}

