/**
 * Uteam API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CityDto } from './cityDto';
import {ITagDto} from "./tagDto";


export interface UserDto {
    id?: number;
    firstName?: string;
    lastName?: string;
    gender?: UserDto.GenderEnum;
    age?: number;
    freeLink?: string;
    ownLink?: string;
    aboutMe?: string;
    readonly dateOfRegistration?: string;
    cityEntityOfResidence?: CityDto;
    nickname: string;
    telegram?: string;
    hideTelegram?: boolean;
    email?: string;
    password?: string;
    hideEmail?: boolean;
    verifiedEmail?: boolean;
    readonly roles: IUserRoles[];
    imageLink?: string;
    banned?: boolean;
    banReason?: string;
    employmentStatus?: UserDto.EmploymentStatusEnum;
    activityStatus?: UserDto.ActivityStatusEnum;
    userSkills?: ITagDto[];
}

export interface IUserAchievement {
  id: number;
  title: string;
  image: string;
}

export interface IUserRoles {
  id: number;
  role: UserDto.RoleEnum;
}

export namespace UserDto {
    export const GenderEnum = {
        Male: 'MALE',
        Female: 'FEMALE'
    } as const;
    export type GenderEnum = typeof GenderEnum[keyof typeof GenderEnum];
    export const RoleEnum = {
        User: 'ROLE_USER',
        Admin: 'ROLE_ADMIN',
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
    export const EmploymentStatusEnum = {
        Employed: 'EMPLOYED',
        Unemployed: 'UNEMPLOYED',
        Freelance: 'FREELANCE',
        OwnBusiness: 'OWN_BUSINESS'
    } as const;
    export type EmploymentStatusEnum = typeof EmploymentStatusEnum[keyof typeof EmploymentStatusEnum];
    export const ActivityStatusEnum = {
        OpenToProposals: 'OPEN_TO_PROPOSALS',
        CanGiveAdvice: 'CAN_GIVE_ADVICE',
        NotActive: 'NOT_ACTIVE'
    } as const;
    export type ActivityStatusEnum = typeof ActivityStatusEnum[keyof typeof ActivityStatusEnum];
}


