/**
 * Uteam API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserProfileProjectDto { 
    id?: number;
    nickname?: string;
    title?: string;
    userId?: number;
    userProfession?: string;
    createdAt?: string;
    owner?: boolean;
}

